@startuml
scale 1024 height
title Adapter mode timing diagram

actor Client
participant Adapter
participant Adaptee

activate Client
Client -> Adaptee: 1.1 <<create>>
activate Adaptee
Client -> Adapter: 1.2 <<create with Adaptee>>
activate Adapter
Client -> Adapter: 2.1 targetMethod()
Adapter -> Adaptee: 2.2 srcMethod()
@enduml