@startuml
scale 1024 height
title Decorator mode timing diagram

actor Client
participant Decorator
participant Component

activate Client
Client -> Component: 1.1 <<create>>
activate Component
Client -> Decorator: 1.2 <<create with Component>>
activate Decorator
Client -> Decorator: 2.1 operation()
Decorator -> Component: 2.2 operation()
Client -> Decorator: 3.1 addedOperation()
Decorator -> Decorator: 3.2 <<operate with self>>
@enduml