@startuml
scale 1024 height
title Facade mode timing diagram

actor Client
participant Facade
participant SystemA
participant SystemB

activate Client
Client -> Facade: wrapOpration()
activate Facade
Facade -> SystemA: oprationA()
activate SystemA
deactivate SystemA
Facade -> SystemB: oprationB()
activate SystemB
deactivate SystemB
@enduml