@startuml Facade
scale 1024 height
class Facade {
}
package "subsystem classes" {
  .Facade --> Classes1
  .Facade --> Classes2
  .Facade --> Classes3
  .Facade --> Classes4
  Classes3 --> Classes6
  Classes1 --> Classes5
  Classes5 -> Classes6
  Classes4 --> Classes5
}

@enduml