@startuml
scale 1024 height
Command <|.. ConcreteCommand
Receiver <-- ConcreteCommand

interface Command{
    excute()
}


class ConcreteCommand {
    -Receiver receiver
    +excute();
}

class Receiver{
    +action();
}
@enduml