@startuml
scale 1024 height
title Mediator pattern class diagram

interface Mediator {
    + registe(int, Colleague)
    + operation(int)
}
class ConMediator
interface Colleague {
    + setMediator(Mediator)
    + sendMsg(int)
    + receiveMsg()
}
class ConColleagueA
class ConColleagueB

Mediator <|.. ConMediator
Colleague <|.. ConColleagueA
Colleague <|.. ConColleagueB

Mediator <- Colleague
ConMediator -> ConColleagueB
ConMediator -> ConColleagueA
@enduml