@startuml
scale 1024 height

Observer <|.. ConcreteObserver
Observer o.. PropertiesSubject

class Observer{
    +update()
}

class ConcreteObserver{
    +update()
}

abstract class PropertiesSubject{
    -Vector<Observer> map
    +addObserver(Observer observer)
    +deleteObserver(Observer observer)
    +notifyObservers();
}

@enduml