@startuml
scale 1024 height


Template <|-- TemplateImpl

abstract class Template{
    +init();
    +preDO();
    +postDo();
    +request()
}

class TemplateImpl {
    +init();
    +preDO();
    +postDo();

}


@enduml