@startuml
scale 1024 height
title Factory Method mode timing diagram

actor Client
participant AFactory
entity AProduct

activate Client
Client -> AFactory: 1.1 createInstance()
activate AFactory
AFactory -> AProduct: 1.2 <<create>>
activate AProduct
deactivate AFactory
Client -> AProduct: 2 <<use>>
@enduml