/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package strategies.mvp.app.view;

import strategies.mvp.app.presenter.SinavOlusturmaPresenter;
import strategies.mvp.app.presenter.strategypattern.ContextSinav;
import strategies.mvp.app.presenter.strategypattern.SinavKolaySorular;

/**
 * <h1>Strategy</h1> Định nghĩa tập hợp các thuật toán, đóng gói từng thuật toán
 * lại, và làm chúng hoán đổi lẫn nhau. Strategy cho phép thuật toán biến đổi
 * độc lập khi người dùng sử dụng chúng.
 * 
 * 
 * @author EMAIL:vuquangtin@gmail.com , tel:0377443333
 * @version 1.0.0
 * @see <a
 *      href="https://github.com/vuquangtin/designpattern">https://github.com

 *      /vuquangtin/designpattern</a>
 *
 */
public class SinavOlusturmaView extends javax.swing.JFrame {

	private SinavOlusturmaPresenter presenter;
	ContextSinav context = new ContextSinav(new SinavKolaySorular());

	public void setPresenter(SinavOlusturmaPresenter pres) {
		presenter = pres;
	}

	public SinavOlusturmaView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jInternalFrame1 = new javax.swing.JInternalFrame();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jComboBox3 = new javax.swing.JComboBox();
		jComboBox4 = new javax.swing.JComboBox();
		jLabel6 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jComboBox5 = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jInternalFrame1.setVisible(true);
		jInternalFrame1.getContentPane().setLayout(
				new org.netbeans.lib.awtextra.AbsoluteLayout());

		jInternalFrame1.getContentPane().add(
				jComboBox1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 230,
						30));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel1.setText("SINAV OLUŞTURMA");
		jInternalFrame1.getContentPane().add(
				jLabel1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 280,
						-1));

		jLabel2.setText("Sınav Adı:");
		jInternalFrame1.getContentPane().add(
				jLabel2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60,
						-1));

		jLabel3.setText("Kategori:");
		jInternalFrame1.getContentPane().add(
				jLabel3,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1,
						-1));

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Kolay", "Orta", "Zor" }));
		jInternalFrame1.getContentPane().add(
				jComboBox2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110,
						230, 30));

		jLabel4.setText("Derslik:");
		jInternalFrame1.getContentPane().add(
				jLabel4,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1,
						-1));

		jLabel5.setText("Gözetmen:");
		jInternalFrame1.getContentPane().add(
				jLabel5,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1,
						-1));

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"c-203", "c-204", "c-205" }));
		jInternalFrame1.getContentPane().add(
				jComboBox3,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150,
						230, 30));

		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Doğan Aydın", "Durmuş Özdemir", "Fırat Aydemir", " " }));
		jInternalFrame1.getContentPane().add(
				jComboBox4,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200,
						230, 30));

		jLabel6.setText("Sınav Kaç Soru:");
		jInternalFrame1.getContentPane().add(
				jLabel6,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1,
						-1));
		jInternalFrame1.getContentPane().add(
				jTextField1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240,
						230, 30));

		jButton1.setText("OLuştur");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(
				jButton1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290,
						190, 40));

		jLabel7.setText("Seviye");
		jInternalFrame1.getContentPane().add(
				jLabel7,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1,
						-1));

		jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Çoktan Seçmeli", "Doğru Yanlış", "Klasik" }));
		jInternalFrame1.getContentPane().add(
				jComboBox5,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 230,
						-1));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jInternalFrame1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 753,
								Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jInternalFrame1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 421,
								Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
		// TODO add your handling code here:
		presenter.DosyaOku();
	}// GEN-LAST:event_formWindowOpened

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		context.executeStrategy3(jComboBox1.getSelectedItem().toString(),
				jComboBox5.getSelectedItem().toString(), jComboBox2
						.getSelectedItem().toString(), jComboBox3
						.getSelectedItem().toString(), jComboBox4
						.getSelectedItem().toString(), Integer
						.valueOf(jTextField1.getText()));
	}// GEN-LAST:event_jButton1ActionPerformed

	public void updateStatusComboBox3(String line) {
		jComboBox1.addItem(line);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JComboBox jComboBox4;
	private javax.swing.JComboBox jComboBox5;
	private javax.swing.JInternalFrame jInternalFrame1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
}
