@startuml


interface Servlet {
    public void init(ServletConfig config) throws ServletException;

    public ServletConfig getServletConfig();

    public void service(ServletRequest req, ServletResponse res)
    throws ServletException, IOException;

    public String getServletInfo();

    public void destroy();
}

interface ServletConfig

abstract class GenericServlet

abstract class HttpServlet {
    protected void service(ServletRequest, ServletResponse)
    throws ServletException, IOException;

    protected void service(HttpServletRequest, HttpServletResponse)
    throws ServletException, IOException;
}

interface ServletContext {

    public String getContextPath();

    public RequestDispatcher getRequestDispatcher(String path);

    public Object getAttribute(String name);

    public void setAttribute(String name, Object object);

    public void removeAttribute(String name);
}

interface RequestDispatcher {
    public void forward(ServletRequest request, ServletResponse response)
    	throws ServletException, IOException;

    public void include(ServletRequest request, ServletResponse response)
    	throws ServletException, IOException;
}

interface ServletRequest
interface ServletResponse
interface HttpServletRequest
interface HttpServletResponse

interface Filter {
    void init(FilterConfig);
    void doFilter(ServletRequest, ServletResponse);
    void destroy();
}

interface FilterChain {
    void doFilter(ServletRequest, ServletResponse);
}

interface FilterConfig

interface HttpSession {
    void setMaxActiveInterval();
    void invalidate();
}

interface EventListener

interface ServletContextListener {
    public void contextInitialized ( ServletContextEvent sce );
    public void contextDestroyed ( ServletContextEvent sce );
}

interface ServletContextAttributeListener {
    public void attributeAdded(ServletContextAttributeEvent scab);
    public void attributeRemoved(ServletContextAttributeEvent scab);
    public void attributeReplaced(ServletContextAttributeEvent scab);
}

class EventObject
class ServletContextEvent
class ServletContextAttributeEvent

interface HttpSessionListener{
    public void sessionCreated ( HttpSessionEvent se );
    public void sessionDestroyed ( HttpSessionEvent se );
}

interface HttpSessionAttributeListener {
    public void attributeAdded(HttpSessionAttributeEvent scab);
    public void attributeRemoved(HttpSessionAttributeEvent scab);
    public void attributeReplaced(HttpSessionAttributeEvent scab);
}

interface HttpSessionActivationListener {
    public void sessionWillPassivate(HttpSessionEvent se);
    public void sessionDidActivate(HttpSessionEvent se);
}

interface HttpSessionBindingListener {
    public void valueBound(HttpSessionBindingEvent event);
    public void valueUnbound(HttpSessionBindingEvent event);
}

class HttpSessionEvent
class HttpSessionAttributeEvent
class HttpSessionBindingEvent

interface ServletRequestListener extends EventListener {
    public void requestDestroyed ( ServletRequestEvent sre );
    public void requestInitialized ( ServletRequestEvent sre );
}

interface ServletRequestAttributeListener extends EventListener {
    public void attributeAdded(ServletRequestAttributeEvent srae);

    public void attributeRemoved(ServletRequestAttributeEvent srae);

    public void attributeReplaced(ServletRequestAttributeEvent srae);
}

class ServletRequestEvent
class ServletRequestAttributeEvent

class ServletRequestWrapper
class ServletResponseWrapper

abstract class ServletInputStream
abstract class ServletOutputStream

class HttpServletRequestWrapper
class HttpServletResponseWrapper

Servlet <|-- GenericServlet
ServletConfig <|-- GenericServlet
GenericServlet <|-- HttpServlet
ServletConfig .--> ServletContext
ServletContext .--> RequestDispatcher
ServletRequest <|-- HttpServletRequest
ServletResponse <|-- HttpServletResponse
Servlet .--> ServletRequest
Servlet .--> ServletResponse
HttpServlet .--> HttpServletRequest
HttpServlet .--> HttpServletResponse
HttpServletResponse .--> Cookie

Filter .--> ServletRequest
Filter .--> ServletResponse
Filter .--> FilterChain
Filter .--> FilterConfig
HttpServletRequest .--> HttpSession

EventObject <|-- ServletContextEvent
EventObject <|-- HttpSessionEvent
EventObject <|-- ServletRequestEvent
ServletRequestEvent <|-- ServletRequestAttributeEvent
ServletRequestEvent <|-- ServletRequestAttributeEvent
HttpSessionEvent <|-- HttpSessionAttributeEvent
HttpSessionEvent <|-- HttpSessionBindingEvent
ServletContextEvent <|-- ServletContextAttributeEvent
EventListener <|-- ServletContextAttributeListener
EventListener <|-- ServletContextListener
EventListener <|-- HttpSessionListener
EventListener <|-- HttpSessionAttributeListener
EventListener <|-- HttpSessionActivationListener
EventListener <|-- HttpSessionBindingListener
EventListener <|-- ServletRequestListener
EventListener <|-- ServletRequestAttributeListener

ServletContextListener .--> ServletContextEvent
ServletContextAttributeListener .--> ServletContextAttributeEvent

HttpSessionListener .--> HttpSessionEvent
HttpSessionAttributeListener .--> HttpSessionAttributeEvent
HttpSessionActivationListener .--> HttpSessionEvent
HttpSessionBindingListener .--> HttpSessionBindingEvent

ServletRequestListener .--> ServletRequestEvent
ServletRequestEvent .--> ServletRequest
ServletRequestAttributeListener .--> ServletRequestAttributeEvent

ServletRequest <|-- ServletRequestWrapper
ServletResponse <|-- ServletResponseWrapper
ServletRequestWrapper *--> ServletRequest
ServletResponseWrapper *--> ServletResponse

InputStream <|-- ServletInputStream
OutputStream <|-- ServletOutputStream

ServletRequestWrapper <|-- HttpServletRequestWrapper
ServletResponseWrapper <|-- HttpServletResponseWrapper

HttpServletRequest <|-- HttpServletRequestWrapper
HttpServletResponse <|-- HttpServletResponseWrapper

@enduml