/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaSwingwithMvpStrategyFacadeSingleton.view;

import java.io.BufferedReader;
import java.io.FileReader;

import JavaSwingwithMvpStrategyFacadeSingleton.facade.FacadeClass;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.Fonksiyonlar;

/**
 *
 * @author mustafa
 */
public class FacadeView extends javax.swing.JInternalFrame {

	/**
	 * Creates new form FacadeView
	 */
	FacadeClass fc = new FacadeClass();
	Fonksiyonlar f = new Fonksiyonlar();

	private static FacadeView instance;

	public static FacadeView getİnstance() {
		if (instance == null) {
			instance = new FacadeView();

		}
		return instance;
	}

	public FacadeView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jDesktopPane4 = new javax.swing.JDesktopPane();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jDesktopPane1 = new javax.swing.JDesktopPane();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jDesktopPane2 = new javax.swing.JDesktopPane();
		jLabel5 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jComboBox5 = new javax.swing.JComboBox();
		jButton3 = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jComboBox6 = new javax.swing.JComboBox();
		jComboBox7 = new javax.swing.JComboBox();
		jButton4 = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();

		addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
			public void internalFrameActivated(
					javax.swing.event.InternalFrameEvent evt) {
				formInternalFrameActivated(evt);
			}

			public void internalFrameClosed(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameClosing(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameDeactivated(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameDeiconified(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameIconified(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameOpened(
					javax.swing.event.InternalFrameEvent evt) {
			}
		});

		jDesktopPane4.setBackground(new java.awt.Color(51, 204, 255));

		jLabel1.setText("Öğretim Üyesi :");

		jLabel2.setText("Gözetmen : ");

		jButton1.setText("Kaydet");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("Gözetmen ve Öğretim Üyesi Kayıt");

		javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(
				jDesktopPane4);
		jDesktopPane4.setLayout(jDesktopPane4Layout);
		jDesktopPane4Layout
				.setHorizontalGroup(jDesktopPane4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jDesktopPane4Layout
										.createSequentialGroup()
										.addGap(16, 16, 16)
										.addGroup(
												jDesktopPane4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel2)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jDesktopPane4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																165,
																Short.MAX_VALUE)
														.addComponent(
																jTextField2))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jDesktopPane4Layout
										.createSequentialGroup()
										.addGap(0, 67, Short.MAX_VALUE)
										.addComponent(
												jLabel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												248,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jDesktopPane4Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												115,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		jDesktopPane4Layout
				.setVerticalGroup(jDesktopPane4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jDesktopPane4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel3)
										.addGap(23, 23, 23)
										.addGroup(
												jDesktopPane4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2))
										.addGap(18, 18, 18)
										.addGroup(
												jDesktopPane4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel1))
										.addGap(18, 18, 18)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												52,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jDesktopPane4.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane4.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane4.setLayer(jTextField1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane4.setLayer(jTextField2,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane4
				.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane4.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jDesktopPane1.setBackground(new java.awt.Color(255, 51, 51));

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel4.setText("Derslikler");

		jLabel6.setText("Bima Adı : ");

		jLabel7.setText("Salon No:");

		jLabel8.setText("Salon Kodu:");

		jLabel9.setText("Derslik Kapasitesi:");

		jButton2.setText("Kaydet");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(
				jDesktopPane1);
		jDesktopPane1.setLayout(jDesktopPane1Layout);
		jDesktopPane1Layout
				.setHorizontalGroup(jDesktopPane1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jDesktopPane1Layout
										.createSequentialGroup()
										.addGroup(
												jDesktopPane1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jDesktopPane1Layout
																		.createSequentialGroup()
																		.addGap(22,
																				22,
																				22)
																		.addGroup(
																				jDesktopPane1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel9))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jDesktopPane1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextField3)
																						.addComponent(
																								jTextField4)
																						.addComponent(
																								jTextField5)
																						.addComponent(
																								jTextField6)))
														.addGroup(
																jDesktopPane1Layout
																		.createSequentialGroup()
																		.addGap(91,
																				91,
																				91)
																		.addComponent(
																				jLabel4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				93,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0,
																				90,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jDesktopPane1Layout
																		.createSequentialGroup()
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				115,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		jDesktopPane1Layout
				.setVerticalGroup(jDesktopPane1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jDesktopPane1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel4)
										.addGap(28, 28, 28)
										.addGroup(
												jDesktopPane1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(21, 21, 21)
										.addGroup(
												jDesktopPane1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(20, 20, 20)
										.addGroup(
												jDesktopPane1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(
																jTextField5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jDesktopPane1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel9)
														.addComponent(
																jTextField6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(
												jButton2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1
				.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(jTextField3,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(jTextField4,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(jTextField5,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(jTextField6,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jDesktopPane2.setBackground(new java.awt.Color(153, 255, 153));

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel5.setText("Sınav Dökümanları");

		jLabel10.setText("Soru Bankası :");

		jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"TasarimDesenleriÇoktanSeçmeliKolay",
				"TasarimDesenleriÇoktanSeçmeliOrta",
				"TasarimDesenleriÇoktanSeçmeliZor",
				"TasarimDesenleriDogruYanlisKolay",
				"TasarimDesenleriDogruYanlisZor",
				"TasarimDesenleriDogruYanlisOrta",
				"TasarimDesenleriKlasikKolay", "TasarimDesenleriKlasikOrta",
				"TasarimDesenleriKlasikZor" }));

		jButton3.setText("DökümanOluştur");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel11.setText("Derslik Seç:");

		jLabel12.setText("Sınav Gözetmeni:");

		jButton4.setText("Yoklama Listesini ve İlan Listesini Olustur");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jLabel13.setText("Sınav Yoklama Listesi Oluşturma");

		jLabel14.setText("Sınıf Seç:");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"1.Sınıf", "2.Sınıf", "3.Sınıf", "4.Sınıf" }));

		javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(
				jDesktopPane2);
		jDesktopPane2.setLayout(jDesktopPane2Layout);
		jDesktopPane2Layout
				.setHorizontalGroup(jDesktopPane2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jDesktopPane2Layout
										.createSequentialGroup()
										.addGap(84, 84, 84)
										.addComponent(jLabel5)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jDesktopPane2Layout
										.createSequentialGroup()
										.addGroup(
												jDesktopPane2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jDesktopPane2Layout
																		.createSequentialGroup()
																		.addContainerGap(
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				193,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jDesktopPane2Layout
																		.createSequentialGroup()
																		.addGap(23,
																				23,
																				23)
																		.addGroup(
																				jDesktopPane2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jDesktopPane2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel10)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addGroup(
																												jDesktopPane2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jComboBox5,
																																0,
																																295,
																																Short.MAX_VALUE)
																														.addGroup(
																																jDesktopPane2Layout
																																		.createSequentialGroup()
																																		.addGap(29,
																																				29,
																																				29)
																																		.addComponent(
																																				jLabel13,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE))))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jDesktopPane2Layout
																										.createSequentialGroup()
																										.addGap(0,
																												0,
																												Short.MAX_VALUE)
																										.addComponent(
																												jButton4))
																						.addGroup(
																								jDesktopPane2Layout
																										.createSequentialGroup()
																										.addGroup(
																												jDesktopPane2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																														.addComponent(
																																jLabel14,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																jLabel12,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																jLabel11,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												jDesktopPane2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jComboBox6,
																																0,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																jComboBox7,
																																0,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																jComboBox1,
																																0,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE))))))
										.addGap(24, 24, 24)));
		jDesktopPane2Layout
				.setVerticalGroup(jDesktopPane2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jDesktopPane2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel5)
										.addGap(27, 27, 27)
										.addGroup(
												jDesktopPane2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel10)
														.addComponent(
																jComboBox5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(
												jButton3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												42,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(19, 19, 19)
										.addComponent(jLabel13)
										.addGap(13, 13, 13)
										.addGroup(
												jDesktopPane2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel14)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jDesktopPane2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBox6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel11))
										.addGap(4, 4, 4)
										.addGroup(
												jDesktopPane2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBox7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel12))
										.addGap(49, 49, 49)
										.addComponent(
												jButton4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(49, Short.MAX_VALUE)));
		jDesktopPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2
				.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2.setLayer(jComboBox5,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2
				.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2
				.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2
				.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2.setLayer(jComboBox6,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2.setLayer(jComboBox7,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2
				.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2
				.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2
				.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane2.setLayer(jComboBox1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jDesktopPane4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jDesktopPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jDesktopPane2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jDesktopPane2)
				.addComponent(jDesktopPane1)
				.addComponent(jDesktopPane4,
						javax.swing.GroupLayout.Alignment.TRAILING));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		f.GözetmenKaydet(jTextField1.getText());
		f.OgretimUyesiKaydet(jTextField2.getText());
		jComboBox7.removeAllItems();
		comboBoxUptade();

	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		fc.SinavOlusturmaSinavOlustur(jComboBox5.getSelectedItem().toString());

	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		f.DerslikKaydet(jTextField3.getText(),
				Integer.valueOf(jTextField4.getText()), jTextField5.getText(),
				Integer.valueOf(jTextField6.getText()));
		jComboBox6.removeAllItems();
		comboBoxUptade();
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:

		fc.SinavYoklamaListeleriSinavYoklamaOlustur(jComboBox6
				.getSelectedItem().toString(), jComboBox7.getSelectedItem()
				.toString());
		fc.SinavYeriIlanListesiSinavYeriOlustur(jComboBox6.getSelectedItem()
				.toString());

	}// GEN-LAST:event_jButton4ActionPerformed

	private void formInternalFrameActivated(
			javax.swing.event.InternalFrameEvent evt) {// GEN-FIRST:event_formInternalFrameActivated
		// TODO add your handling code here:
		comboBoxUptade();

	}// GEN-LAST:event_formInternalFrameActivated

	public void comboBoxUptade() {
		String path6 = "Content\\Facade\\Gozetmenler.txt";
		String path5 = "Content\\Facade\\Derslikler.txt";
		try {

			BufferedReader bf = new BufferedReader(new FileReader(path5));
			BufferedReader bf2 = new BufferedReader(new FileReader(path6));

			String line = bf.readLine();
			String line2 = bf2.readLine();

			while (line != null) {
				jComboBox6.addItem(line);
				line = bf.readLine();

			}
			while (line2 != null) {
				jComboBox7.addItem(line2);
				line2 = bf2.readLine();
			}

			System.out.println("Okuma İşlemi Başarılı");

		} catch (Exception hata) {
			hata.printStackTrace();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox5;
	private javax.swing.JComboBox jComboBox6;
	private javax.swing.JComboBox jComboBox7;
	private javax.swing.JDesktopPane jDesktopPane1;
	private javax.swing.JDesktopPane jDesktopPane2;
	private javax.swing.JDesktopPane jDesktopPane4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	// End of variables declaration//GEN-END:variables

}
