/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaSwingwithMvpStrategyFacadeSingleton.view;


import javax.swing.JOptionPane;

import JavaSwingwithMvpStrategyFacadeSingleton.presenter.SoruBankasiPresenter;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.CoktanSecmeliKolaySoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.CoktanSecmeliOrtaSoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.CoktanSecmeliZorSoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.Context;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.ContextListele;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.DogruYanlisKolaySoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.DogruYanlisOrtaSoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.DogruYanlisZorSoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.KlasikKolaySoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.KlasikOrtaSoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.KlasikZorSoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.ListeleKolaySoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.ListeleOrtaSoru;
import JavaSwingwithMvpStrategyFacadeSingleton.presenter.strategy.ListeleZorSoru;

/**
 *
 * @author mustafa
 */
public class SoruBankasiView extends javax.swing.JFrame {

    /**
     * Creates new form SoruBankasıView
     */
    private SoruBankasiPresenter presenter;
    
    Context context = new Context(new CoktanSecmeliKolaySoru());
    Context context2 = new Context(new CoktanSecmeliOrtaSoru());
    Context context3 = new Context(new CoktanSecmeliZorSoru());
    Context context4 = new Context(new DogruYanlisKolaySoru());
    Context context5 = new Context(new DogruYanlisOrtaSoru());
    Context context6 = new Context(new DogruYanlisZorSoru());
    Context context7 = new Context(new KlasikKolaySoru());
    Context context8 = new Context(new KlasikOrtaSoru());
    Context context9 = new Context(new KlasikZorSoru());
    ContextListele context10=new ContextListele(new ListeleKolaySoru());
    ContextListele context11=new ContextListele(new ListeleOrtaSoru());
    ContextListele context12=new ContextListele(new ListeleZorSoru());
    
  
    private static SoruBankasiView instance;
    public static SoruBankasiView getİnstance(){
        if(instance==null)
        {
            instance=new SoruBankasiView();
            
        }
        return instance;
    }
    
    public SoruBankasiView() { //PRİVATE
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });





        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        presenter.DosyaOku();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        context10.executeStrategy2(jComboBox4.getSelectedItem().toString());
        context11.executeStrategy2(jComboBox4.getSelectedItem().toString());
        context12.executeStrategy2(jComboBox4.getSelectedItem().toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

       // presenter.messageBox(jTextField3.getText());

        context.executeStrategy(jComboBox1.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString(),
            jComboBox3.getSelectedItem().toString(),
            jTextField1.getText(),jTextField2.getText(),Integer.valueOf(jTextField3.getText()));

        context2.executeStrategy(jComboBox1.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString(),
            jComboBox3.getSelectedItem().toString(),
            jTextField1.getText(),jTextField2.getText(),Integer.valueOf(jTextField3.getText()));
        context3.executeStrategy(jComboBox1.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString(),
            jComboBox3.getSelectedItem().toString(),
            jTextField1.getText(),jTextField2.getText(),Integer.valueOf(jTextField3.getText()));
        context4.executeStrategy(jComboBox1.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString(),
            jComboBox3.getSelectedItem().toString(),
            jTextField1.getText(),jTextField2.getText(),Integer.valueOf(jTextField3.getText()));
        context5.executeStrategy(jComboBox1.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString(),
            jComboBox3.getSelectedItem().toString(),
            jTextField1.getText(),jTextField2.getText(),Integer.valueOf(jTextField3.getText()));
        context6.executeStrategy(jComboBox1.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString(),
            jComboBox3.getSelectedItem().toString(),
            jTextField1.getText(),jTextField2.getText(),Integer.valueOf(jTextField3.getText()));
        context7.executeStrategy(jComboBox1.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString(),
            jComboBox3.getSelectedItem().toString(),
            jTextField1.getText(),jTextField2.getText(),Integer.valueOf(jTextField3.getText()));
        context8.executeStrategy(jComboBox1.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString(),
            jComboBox3.getSelectedItem().toString(),
            jTextField1.getText(),jTextField2.getText(),Integer.valueOf(jTextField3.getText()));
        context9.executeStrategy(jComboBox1.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString(),
            jComboBox3.getSelectedItem().toString(),
            jTextField1.getText(),jTextField2.getText(),Integer.valueOf(jTextField3.getText()));

    }//GEN-LAST:event_jButton1ActionPerformed

  
    public void setPresenter(SoruBankasiPresenter pres)
    {
        presenter = pres;
    }
    
    
    public void updateStatusComboBox2(String line)
    {
        jComboBox1.addItem(line);
    }
    
    public void updateMessageBox()
    {
        JOptionPane.showMessageDialog(null, "Puan Değerini sayı girmelisiniz!","Hatalı Giriş",-1);
        
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

  
}
