@startuml
interface StrategyInterface {
  exe()
} 
StrategyA : exe()
StrategyB : exe()

StrategyInterface <|.. StrategyA
StrategyInterface <|.. StrategyB

StrategyContext *-- StrategyInterface

@enduml